#!/bin/sh
#
# Shell script for launching morpho from unix systems
#
# '$RCSfile: morpho,v $'
# '$Author: brooke $'
# '$Date: 2002-10-28 17:32:17 $'
# '$Revision: 1.19 $'

if ! ls $JAVA_HOME/bin/ | grep -q java; then
 echo ----------------------------------------------------------------------
 echo ----------------------------------------------------------------------
 echo ---------------------------- N O T E ---------------------------------
 echo ---- YOU MUST SET THE JAVA_HOME ENVIRONMENT VARIABLE TO POINT TO -----
 echo --- YOUR JDK OR JRE INSTALLATION DIRECTORY BEFORE RUNNING MORPHO! ----
 echo ----- Note that Morpho may not work correctly with non-SUN JVMs, -----
 echo --------------------- such as gcj or kafee. --------------------------
 echo ----------------------------------------------------------------------
 echo ----------------------------------------------------------------------
 exit
fi



XMLP=./lib/xercesImpl.jar
API=./lib/xmlParserAPIs.jar
XALAN=./lib/xalan.jar
# DMC=./lib/morpho.jar
DMC=./build/morpho.jar
# CFG=./lib/morpho-config.jar
CFG=./build/morpho-config.jar
JLF=./lib/shippedIcons.jar
HTP=./lib/httpclient.jar
ITS=./lib/itislib.jar
JSE=./lib/jsse.jar
JCE=./lib/jcert.jar
JNE=./lib/jnet.jar  
LAF=./lib/kunststoff.jar
CPATH=$JAVA_HOME/jre/lib/rt.jar:$XMLP:$API:$XALAN:$DMC:$CFG:$JLF:$HTP:$ITS:$JSE:$JCE:$JNE:$LAF
echo "----------------------------------"

$JAVA_HOME/bin/java -version

echo "----------------------------------"
$JAVA_HOME/bin/java -Xmx512m -Xss1m -cp $CPATH edu.ucsb.nceas.morpho.Morpho
