#!/bin/sh
#
# Shell script for launching morpho from unix systems
#
# '$RCSfile: morpho,v $'
# '$Author: higgins $'
# '$Date: 2002-08-20 18:17:25 $'
# '$Revision: 1.14 $'

XMLP=./lib/xercesImpl.jar
API=./lib/xmlParserAPIs.jar
XALAN=./lib/xalan.jar
DMC=./lib/morpho.jar
CFG=./lib/morpho-config.jar
JLF=./lib/jlfgr-1_0.jar
HTP=./lib/httpclient.jar
ITS=./lib/itislib.jar
JSE=./lib/jsse.jar
JCE=./lib/jcert.jar
JNE=./lib/jnet.jar  
LAF=./lib/kunststoff.jar
CPATH=$XMLP:$API:$XALAN:$DMC:$CFG:$JLF:$HTP:$ITS:$JSE:$JCE:$JNE:$LAF
java -Xmx512m -cp $CPATH edu.ucsb.nceas.morpho.Morpho
