/**
 *        Name: RSFrame.java
 *     Purpose: A Class for displaying search result sets
 *   Copyright: 2000 Regents of the University of California and the
 *              National Center for Ecological Analysis and Synthesis
 *     Authors: Dan Higgins
 *
 *     Version: '$Id: RSFrame.java,v 1.15 2001-04-26 00:10:06 jones Exp $'
 */


package edu.ucsb.nceas.querybean;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.table.*;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.ListSelectionEvent;
import java.io.*;
import java.util.*;
import edu.ucsb.nceas.dtclient.*;
import java.net.URL;

public class RSFrame extends javax.swing.JFrame
{
    edu.ucsb.nceas.metaedit.AbstractMdeBean mde;
    JTabbedPane tab;
    MouseListener popupListener;
    
    JMenuItem ShowmenuItem;
    JMenuItem SavemenuItem;
    JMenuItem EditmenuItem;
    JMenuItem RelatedmenuItem;
    
    public boolean local = true;
    // local or remote results?
    
//    PropertyResourceBundle options;
    ConfigXML config;
    String MetaCatServletURL = null;
    
    Hashtable relations;
    int docidcol = 0;   // column which contains docid
	public RSFrame()
	{
	    
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		getContentPane().setLayout(new BorderLayout(0,0));
		setSize(745,351);
		setVisible(false);
		RS_Panel.setLayout(new BorderLayout(0,0));
		getContentPane().add(BorderLayout.CENTER,RS_Panel);
		RS_Panel.setBackground(java.awt.Color.white);
		RS_Panel.setBounds(0,0,745,351);
		JPanel1.setLayout(new BorderLayout(0,0));
		RS_Panel.add(BorderLayout.NORTH, JPanel1);
		JPanel1.setBounds(0,0,745,46);
		JPanel2.setLayout(new FlowLayout(FlowLayout.CENTER,5,5));
		JPanel1.add(BorderLayout.CENTER, JPanel2);
		JPanel2.setBounds(233,0,285,46);
		TitleLabel.setText("Results of Search");
		JPanel2.add(TitleLabel);
		TitleLabel.setForeground(java.awt.Color.black);
		TitleLabel.setBounds(92,5,101,15);
		JPanel3.setLayout(new FlowLayout(FlowLayout.CENTER,5,5));
		JPanel1.add(BorderLayout.WEST, JPanel3);
		JPanel3.setBounds(0,0,233,46);
		JScrollPane3.setOpaque(true);
		JPanel3.add(JScrollPane3);
		JScrollPane3.setBounds(5,5,223,33);
		QueryStringTextArea.setColumns(20);
		QueryStringTextArea.setRows(2);
		QueryStringTextArea.setText("Query generated on:Wed Dec 27 10:23:30 PST 2000");
		QueryStringTextArea.setLineWrap(true);
		JScrollPane3.getViewport().add(QueryStringTextArea);
		QueryStringTextArea.setBounds(0,0,220,30);
		JPanel4.setLayout(new GridLayout(2,1,0,0));
		JPanel1.add(BorderLayout.EAST, JPanel4);
		JPanel4.setBounds(518,0,227,46);
		JCheckBox4.setText("Refine Search (Using these Results)");
		JCheckBox4.setActionCommand("Refine Search (Using these Results)");
		JPanel4.add(JCheckBox4);
		JCheckBox4.setFont(new Font("Dialog", Font.PLAIN, 12));
		JCheckBox4.setBounds(0,0,227,23);
		JCheckBox4.setVisible(false);
		RSScrollPane.setOpaque(true);
		RS_Panel.add(BorderLayout.CENTER, RSScrollPane);
		RSScrollPane.setBounds(0,46,745,305);
		RSScrollPane.getViewport().add(JTable1);
		JTable1.setBounds(0,0,742,0);
		saveFileDialog.setMode(FileDialog.SAVE);
		saveFileDialog.setTitle("Save");
		//$$ saveFileDialog.move(24,336);
		//}}

		//{{INIT_MENUS
		//}}
		SymAction lSymAction = new SymAction();
		
		popupListener = new PopupListener();
		RelatedmenuItem = new JMenuItem("Show Related Documents");
		RelatedmenuItem.addActionListener(lSymAction);
		popup.add(RelatedmenuItem);
		ShowmenuItem = new JMenuItem("Display Document");
		ShowmenuItem.addActionListener(lSymAction);
        popup.add(ShowmenuItem);
		EditmenuItem = new JMenuItem("Edit Document");
		EditmenuItem.addActionListener(lSymAction);
        popup.add(EditmenuItem);
		SavemenuItem = new JMenuItem("Save Document as Local File...");
		SavemenuItem.addActionListener(lSymAction);
        popup.add(SavemenuItem);
		
		
    try {
        config = new ConfigXML("lib/config.xml");
//      options = (PropertyResourceBundle)PropertyResourceBundle.getBundle("client");
      MetaCatServletURL = config.get("MetaCatServletURL", 0);
    }
    catch (Exception e) {System.out.println("Could not locate properties file!");}
		
		    JTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            JTable1.addMouseListener(popupListener);
		    
  /*          ListSelectionModel rowSM = JTable1.getSelectionModel();
            rowSM.addListSelectionListener(new ListSelectionListener() {
                public void valueChanged(ListSelectionEvent e) {
                    //Ignore extra messages.
                    if (e.getValueIsAdjusting()) return;
                    
                    ListSelectionModel lsm = (ListSelectionModel)e.getSource();
                    if (lsm.isSelectionEmpty()) {
                        System.out.println("No rows are selected.");
                    } else {
                        if (local) {
                        int selectedRow = lsm.getMinSelectionIndex();
                        String filename = (String)JTable1.getModel().getValueAt(selectedRow, 0);
                        File file = new File("xmlfiles/"+filename);
                        DocFrame df = new DocFrame(file);
                        df.setVisible(true);
                        df.writeInfo();
                        }
                        else //assume data is from remote server
                        {
                            int selectedRow = lsm.getMinSelectionIndex();
                            String qtext1 = (String)JTable1.getModel().getValueAt(selectedRow, 0);
                                   // assumes that docid is in first column of table
	                        String respType = "xml";
	//                        if (HTMLOutput1.isSelected()) respType = "html";
	                        try {
		                        URL url = new URL(MetaCatServletURL);
		                        HttpMessage msg = new HttpMessage(url);
		                        Properties prop = new Properties();
		                        prop.put("action","getdocument");
		                        prop.put("docid",qtext1);
		                        prop.put("qformat",respType);
		    
		    
		                        InputStream in = msg.sendPostMessage(prop);
		                        String message_sent = MetaCatServletURL+msg.getArgString();
		    
		                        //OutputTextArea.setText(msg.contype+"\n");
		                        StringBuffer txt = new StringBuffer();
		                        int x;
		                        try {
		                        while((x=in.read())!=-1) {
		                            txt.append((char)x);
		                           }
		                        }
		                        catch (Exception f) {}
		                        String txt1 = txt.toString();
		                        DocFrame df = new DocFrame("Selected Document", txt1);
                                df.setVisible(true);
		                        in.close();
		                    }
		                catch (Exception ee) {
		                    ee.printStackTrace();
		                    }                        
                        }
                    }
                }
            });
		
	*/	
	}


    public void setEditor (edu.ucsb.nceas.metaedit.AbstractMdeBean mde) {
       this.mde = mde; 
    }
    public void setTabbedPane (JTabbedPane tp) {
       this.tab = tp; 
    }
    public void setLocal(boolean loc) {
        local = loc;
    }

	public RSFrame(String sTitle)
	{
		this();
		setTitle(sTitle);
	}

	public void setVisible(boolean b)
	{
		if (b)
			setLocation(50, 50);
		super.setVisible(b);
	}

	static public void main(String args[])
	{
		(new RSFrame()).setVisible(true);
	}

	public void addNotify()
	{
		// Record the size of the window prior to calling parents addNotify.
		Dimension size = getSize();

		super.addNotify();

		if (frameSizeAdjusted)
			return;
		frameSizeAdjusted = true;

		// Adjust size of frame according to the insets and menu bar
		Insets insets = getInsets();
		javax.swing.JMenuBar menuBar = getRootPane().getJMenuBar();
		int menuBarHeight = 0;
		if (menuBar != null)
			menuBarHeight = menuBar.getPreferredSize().height;
		setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height + menuBarHeight);
	}

	// Used by addNotify
	boolean frameSizeAdjusted = false;

	//{{DECLARE_CONTROLS
	javax.swing.JPanel RS_Panel = new javax.swing.JPanel();
	javax.swing.JPanel JPanel1 = new javax.swing.JPanel();
	javax.swing.JPanel JPanel2 = new javax.swing.JPanel();
	javax.swing.JLabel TitleLabel = new javax.swing.JLabel();
	javax.swing.JPanel JPanel3 = new javax.swing.JPanel();
	javax.swing.JScrollPane JScrollPane3 = new javax.swing.JScrollPane();
	javax.swing.JTextArea QueryStringTextArea = new javax.swing.JTextArea();
	javax.swing.JPanel JPanel4 = new javax.swing.JPanel();
	javax.swing.JCheckBox JCheckBox4 = new javax.swing.JCheckBox();
	javax.swing.JScrollPane RSScrollPane = new javax.swing.JScrollPane();
	javax.swing.JTable JTable1 = new javax.swing.JTable();
	java.awt.FileDialog saveFileDialog = new java.awt.FileDialog(this);
	//}}
    //Create the popup menu.
        javax.swing.JPopupMenu popup = new JPopupMenu();

	//{{DECLARE_MENUS
	//}}

	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == ShowmenuItem) 
				ShowMenuItem_actionPerformed(event);
	        else if (object == EditmenuItem)
	            EditMenuItem_actionPerformed(event);
	        else if (object == RelatedmenuItem)
	            RelatedMenuItem_actionPerformed(event);
	        else if (object == SavemenuItem)
	            SavemenuItem_actionPerformed(event);
	        
		}
	}


	void SavemenuItem_actionPerformed(java.awt.event.ActionEvent event)
	{
	   int selectedRow = JTable1.getSelectedRow();
	    if (local) {
	        
	    }
	    else {
	        saveFileDialog.setVisible(true);
	        String filename = saveFileDialog.getFile();
	        if (filename!=null) {
	            filename = saveFileDialog.getDirectory()+filename;
//	            System.out.println(filename);
	            File file = new File(filename);
 
            String qtext2 = (String)JTable1.getModel().getValueAt(selectedRow, docidcol);
                    // assumes that docid is in docidcol column of table
            String qtext1 = docidFilter(qtext2);
	        String respType = "xml";
	        try {
		        URL url = new URL(MetaCatServletURL);
		        if (qtext2.startsWith("http://")) {
//		            System.out.println("URL used = "+qtext1);
		            url = new URL(qtext1);  // case where actual http URL data doc is specified    
		        }
		        HttpMessage msg = new HttpMessage(url);
		        Properties prop = new Properties();
		        if (!qtext2.startsWith("http://")) {
		            System.out.println("qtext1 = "+qtext1);

		            if (qtext2.startsWith("metacatdata://")) {
		                prop.put("action","read");
		                prop.put("docid",qtext1);
		                prop.put("qformat","bin");
		            }
		            else {
		                prop.put("action","read");
		                prop.put("docid",qtext1);
		                prop.put("qformat",respType);
		            }
		        }
		    
		        InputStream in = msg.sendPostMessage(prop);
		        String message_sent = MetaCatServletURL+msg.getArgString();
		        
		        FileOutputStream fw = new FileOutputStream(file);
		        int x;
		        try {
		        while((x=in.read())!=-1) {
		             fw.write(x);
		            }
		            fw.close();
		        }
		        catch (Exception f) {}
		        in.close();
		        }
		        catch (Exception ee) {
		           ee.printStackTrace();
		        }                        
	            
	        }
	    }
	}


	void RelatedMenuItem_actionPerformed(java.awt.event.ActionEvent event)
	{
	   int selectedRow = JTable1.getSelectedRow();
	   if (local) {
            JOptionPane.showMessageDialog(null,"This feature not yet enabled for local files!","Alert",JOptionPane.INFORMATION_MESSAGE); 
	   }
	   else {
            String qtext1 = (String)JTable1.getModel().getValueAt(selectedRow, 0);
                    // assumes that docid is in first column of table
            if (relations!=null) { 
                if (relations.size()>0) {
	            Vector relationsVector = (Vector)relations.get(qtext1);
	            
	            if (relationsVector!=null) {
	            
	            String[] relationheaders = new String[3];
	            relationheaders[0] = "Relationship";
	            relationheaders[1] = "Related Document";
	            relationheaders[2] = "Related Doucment Type";
                DefaultTableModel dtm = new DefaultTableModel(relationheaders,0);
	            
	            
	            for (Enumeration e = relationsVector.elements();e.hasMoreElements();) {
	                String[] rels = (String[])e.nextElement();
	        //        System.out.println("relationtype = "+rels[0]);
	        //        System.out.println("relationdoc = "+rels[1]);
	        //        System.out.println("relationdoctype = "+rels[2]);
	                dtm.addRow(rels);
	            }
                JTable relationTable = new JTable(dtm);
                RSFrame rs = new RSFrame("Related Documents");
                rs.setSize(800,240);
                rs.setEditor(mde);
                rs.docidcol = 1;
                rs.TitleLabel.setText("Related Documents");
           //     rs.setTabbedPane(tabbedPane);
                 rs.setVisible(true);
                 rs.local=false;
                 JTable ttt = relationTable;
                 TableModel tm = ttt.getModel();
                 rs.JTable1.setModel(tm);
                 rs.JTable1.setColumnModel(ttt.getColumnModel());
                 rs.pack();
                }
	            else {  // relationsVector is null
	               JOptionPane.showMessageDialog(null,"No related documents were found.","Alert",JOptionPane.INFORMATION_MESSAGE);
	            }
	            }
	            else {  // number of related docs is zero
	               JOptionPane.showMessageDialog(null,"No related documents were found.","Alert",JOptionPane.INFORMATION_MESSAGE);
	            }
	        }
	        else {  // relations is null
                 JOptionPane.showMessageDialog(null,"No related documents were found.","Alert",JOptionPane.INFORMATION_MESSAGE); 
	        }
	   }
	 
	}

	void ShowMenuItem_actionPerformed(java.awt.event.ActionEvent event)
	{
	   int selectedRow = JTable1.getSelectedRow();
	   if (local) {
	    if (selectedRow>-1) {
            String filename = (String)JTable1.getModel().getValueAt(selectedRow, docidcol);
            File file = new File(filename);
            DocFrame df = new DocFrame(file);
            df.setVisible(true);
            df.writeInfo();
//            df.setDoctype("eml-dataset");
            
	    }
	   }
	   else {
            String qtext2 = (String)JTable1.getModel().getValueAt(selectedRow, docidcol);
                    // assumes that docid is in docidcol column of table
            String qtext1 = docidFilter(qtext2);
	        String respType = "xml";
	        try {
		        URL url = new URL(MetaCatServletURL);
		        HttpMessage msg = new HttpMessage(url);
		        Properties prop = new Properties();
		        prop.put("action","read");
		        prop.put("docid",qtext1);
		        prop.put("qformat",respType);
		    
		    
		        InputStream in = msg.sendPostMessage(prop);
		        String message_sent = MetaCatServletURL+msg.getArgString();
		        
//		        File tmp = new File("tmp/");
//		        if (!tmp.exists()) {
//		            tmp.mkdir();
//		        }
//		        File temp = new File("tmp/temp.xml");
//		        FileWriter fw = new FileWriter(temp);
		        StringBuffer txt = new StringBuffer();
		        int x;
		        try {
		        while((x=in.read())!=-1) {
		             txt.append((char)x);
//		             fw.write(x);
		            }
//		            fw.close();
//		            if (mde!=null) {
//		                mde.openDocument(temp);
//		                tab.setSelectedIndex(0);
//		            }
//		            else {System.out.println("mde is null in RSFrame class");}
		        }
		        catch (Exception f) {}
		        String txt1 = txt.toString();
		        DocFrame df = new DocFrame("Selected Document", txt1);
                df.setVisible(true);
		        in.close();
		        }
		        catch (Exception ee) {
		           ee.printStackTrace();
		        }                        
	   }
	}
	
	String docidFilter(String in) {
	    String res = in;
	    if (docidcol!=0) {   // for special cases where docid must be filtered
	        // currently a docidcol of 1 indicates a related docs table
	        if (docidcol==1) {
	            if (in.indexOf("docid=")>0) {
	                int start = in.indexOf("docid=")+6;
	                int end = in.length();
	                res = in.substring(start,end);
	                System.out.println("res id is "+res);
	            }
	        }
	    }
	    return res;
	}
	
	
	void EditMenuItem_actionPerformed(java.awt.event.ActionEvent event)
	{
	   int selectedRow = JTable1.getSelectedRow();
	   if (local) {
	    if (selectedRow>-1) {
            String filename = (String)JTable1.getModel().getValueAt(selectedRow, docidcol);
            File temp = new File(filename);
		            if (mde!=null) {
		                mde.openDocument(temp);
		                tab.setSelectedIndex(0);
		            }
		            else {System.out.println("mde is null in RSFrame class");}
	    }
	   }
	   else {
            String qtext2 = (String)JTable1.getModel().getValueAt(selectedRow, docidcol);
                    // assumes that docid is in docidcol column of table
            String qtext1 = docidFilter(qtext2);
	        String respType = "xml";
	        try {
		        URL url = new URL(MetaCatServletURL);
		        HttpMessage msg = new HttpMessage(url);
		        Properties prop = new Properties();
		        prop.put("action","read");
		        prop.put("docid",qtext1);
		        prop.put("qformat",respType);
		    
		    
		        InputStream in = msg.sendPostMessage(prop);
		        String message_sent = MetaCatServletURL+msg.getArgString();
		        
		        File tmp = new File("tmp/");
		        if (!tmp.exists()) {
		            tmp.mkdir();
		        }
		        File temp = new File("tmp/temp.xml");
		        FileWriter fw = new FileWriter(temp);
		        int x;
		        try {
		        while((x=in.read())!=-1) {
		             fw.write(x);
		            }
		            fw.close();
		            if (mde!=null) {
		                mde.openDocument(temp);
		                tab.setSelectedIndex(0);
		            }
		            else {System.out.println("mde is null in RSFrame class");}
		        }
		        catch (Exception f) {}
		        in.close();
		        }
		        catch (Exception ee) {
		           ee.printStackTrace();
		        }                        
	   }
	}


    class PopupListener extends MouseAdapter {
        // on the Mac, popups are triggered on mouse pressed, while mouseReleased triggers them
        // on the PC; use the trigger flag to record a trigger, but do not show popup until the
        // mouse released event
        boolean trigger = false;
              public void mousePressed(MouseEvent e) {
                 // maybeShowPopup(e);
                 if (e.isPopupTrigger()) {
                    trigger = true;
                 }  
              }

              public void mouseReleased(MouseEvent e) {
                  maybeShowPopup(e);
              }

              private void maybeShowPopup(MouseEvent e) {
                  if ((e.isPopupTrigger())||(trigger)) {
                     trigger = false;
                     popup.show(e.getComponent(), e.getX(), e.getY());
                  }
                  int selrow = ((JTable)e.getComponent()).rowAtPoint(new Point(e.getX(), e.getY()));
                  ((JTable)e.getComponent()).setRowSelectionInterval(selrow,selrow);    
              }
    }

}
