package edu.ucsb.nceas.morpho.plugins.datapackagewizard;

import edu.ucsb.nceas.morpho.framework.AbstractUIPage;

/**
 * An interface defines a method to get UI page base on pageID. 
 * So user can overwrite the getUIPage method in WizardPageLibrary class.
 * @author tao
 *
 */
public interface WizardPageLibraryInterface {
	
	public AbstractUIPage getPage(String pageID);
	
	/**
	 * Sets the size of TextImportAttributePage. TextImportAttirubtePage
	 * is dynamically generated by the page library. So we need to know its size.
	 * @param size
	 */
	public void setTextImportAttributePagesSize(int size);
	
	/**
	 * Gets the size of text import attribute page size
	 * @return
	 */
	public int getTextImportAttributePagesSize();

}
